import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

import Header from '@/app/components/header';
import { Roboto } from 'next/font/google';

import './globals.css';
import cn from './utils/cn';

const inter = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-black-500 text-white h-screen gap-0',
          inter.className
        )}
      >
        <Header className="" />

        {children}
      </body>
    </html>
  );
}

export default RootLayout;
